/**
 * Literature Verifier
 * Ensures every returned parameter can be traced to peer-reviewed literature
 *
 * Three verification levels:
 * 1. VERIFIED: Parameter from literature (DOI, PMID, or URL provided)
 * 2. FLAGGED: Parameter from literature but missing assay conditions
 * 3. PENDING: Parameter from LLM - requires manual verification
 * 4. UNVERIFIABLE: Parameter is default/user-supplied (no literature backing)
 */

export type VerificationLevel = "verified" | "flagged" | "pending" | "unverifiable";

export interface LiteratureReference {
  doi?: string; // Digital Object Identifier
  pmid?: string; // PubMed ID
  url?: string; // Direct URL to source
  title?: string;
  authors?: string;
  year?: number;
  source?: string; // "brenda", "pubmed", "core", "llm", "user"
}

export interface VerificationResult {
  level: VerificationLevel;
  message: string;
  reference?: LiteratureReference;
  confidence: number; // 0-1 scale
  requiresManualReview: boolean;
}

/**
 * Helper to create a verification result with consistent structure.
 */
function createVerificationResult(
  level: VerificationLevel,
  message: string,
  confidence: number,
  requiresManualReview: boolean,
  reference?: LiteratureReference,
): VerificationResult {
  return {
    level,
    message,
    reference,
    confidence,
    requiresManualReview,
  };
}

/**
 * Verify a parameter against literature backing
 * BACKING: ADR 0011 - Parameter Provenance
 */
export function verifyParameterAgainstLiterature(
  parameterName: string,
  value: number,
  origin: "resolved" | "keyword" | "llm" | "user" | "default",
  reference?: LiteratureReference,
  assayConditionsComplete?: boolean,
): VerificationResult {
  // User-supplied parameters: no verification needed
  if (origin === "user") {
    return createVerificationResult("unverifiable", "Parameter supplied by user; trust as stated", 1.0, false);
  }

  // Default parameters: lower confidence
  if (origin === "default") {
    return createVerificationResult(
      "unverifiable",
      `Parameter is system default (${value}); not from literature`,
      0.3,
      false,
    );
  }

  // LLM-supplied: requires manual verification
  if (origin === "llm") {
    return createVerificationResult(
      "pending",
      "Parameter generated by LLM; requires manual literature verification before publication",
      0.4,
      true,
      reference,
    );
  }

  // Keyword-matched: medium confidence
  if (origin === "keyword") {
    return createVerificationResult(
      "flagged",
      "Parameter matched via keyword; not directly from literature. Use as estimate only.",
      0.6,
      false,
      reference,
    );
  }

  // Resolved from literature (origin === "resolved")
  if (!reference || !reference.doi && !reference.pmid && !reference.url) {
    return createVerificationResult(
      "flagged",
      "Parameter from literature but source not fully documented",
      0.7,
      false,
      reference,
    );
  }

  // Full literature backing with DOI/PMID
  if (!assayConditionsComplete) {
    return createVerificationResult(
      "flagged",
      `Parameter from ${reference.source || "literature"} but assay conditions incomplete (STRENDA Req 1-3)`,
      0.8,
      false,
      reference,
    );
  }

  // Fully verified: literature + complete assay conditions
  return createVerificationResult(
    "verified",
    `Parameter from ${reference.source || "literature"} with complete assay conditions per STRENDA`,
    0.95,
    false,
    reference,
  );
}

/**
 * Get publication-ready verification message
 * Used when exporting results for peer review or publication
 */
export function getPublicationVerification(result: VerificationResult): string {
  switch (result.level) {
    case "verified":
      return `✅ ${result.message}. Confidence: ${(result.confidence * 100).toFixed(0)}%. ${result.reference?.doi ? `DOI: ${result.reference.doi}` : result.reference?.pmid ? `PMID: ${result.reference.pmid}` : ""}`;

    case "flagged":
      return `⚠️  ${result.message}. Confidence: ${(result.confidence * 100).toFixed(0)}%. Recommend obtaining complete assay conditions.`;

    case "pending":
      return `❌ ${result.message}. Confidence: ${(result.confidence * 100).toFixed(0)}%. DO NOT PUBLISH without manual verification.`;

    case "unverifiable":
      return `ℹ️  ${result.message}. Confidence: ${(result.confidence * 100).toFixed(0)}%.`;
  }
}

/**
 * Check if parameter can be safely published
 */
export function canPublish(result: VerificationResult): boolean {
  // Can publish if: verified OR flagged with literature + assay conditions
  if (result.level === "verified") return true;
  if (result.level === "flagged" && result.reference?.doi) return true; // Flagged but has DOI
  return false;
}

/**
 * Verify entire parameter set for publication
 */
export interface PublicationAudit {
  readyToPublish: boolean;
  verifiedCount: number;
  flaggedCount: number;
  pendingCount: number;
  unverifiableCount: number;
  summary: string;
  issues: string[];
}

export function auditForPublication(
  results: Record<string, VerificationResult>,
): PublicationAudit {
  // Count results by level
  const counts: Record<VerificationLevel, number> = {
    verified: 0,
    flagged: 0,
    pending: 0,
    unverifiable: 0,
  };
  const issues: string[] = [];

  for (const [param, result] of Object.entries(results)) {
    counts[result.level]++;

    if (result.level === "flagged") {
      issues.push(`${param}: ${result.message}`);
    } else if (result.level === "pending") {
      issues.push(`${param}: ⚠️  REQUIRES MANUAL VERIFICATION - ${result.message}`);
    }
  }

  const readyToPublish = counts.pending === 0 && (counts.verified + counts.flagged > 0);

  return {
    readyToPublish,
    verifiedCount: counts.verified,
    flaggedCount: counts.flagged,
    pendingCount: counts.pending,
    unverifiableCount: counts.unverifiable,
    summary: readyToPublish
      ? `Publication ready: ${counts.verified} verified, ${counts.flagged} with literature backing`
      : `Not ready: ${counts.pending} pending, ${counts.unverifiable} unverifiable`,
    issues,
  };
}

/**
 * Generate publication-ready parameter table with verification status
 */
export function generatePublicationTable(
  results: Record<string, VerificationResult>,
): string {
  const rows: string[] = [
    "| Parameter | Value | Verification | Confidence | Source |",
    "|-----------|-------|--------------|------------|--------|",
  ];

  for (const [param, result] of Object.entries(results)) {
    const source = result.reference?.doi
      ? `[DOI](https://doi.org/${result.reference.doi})`
      : result.reference?.pmid
        ? `[PMID](https://pubmed.ncbi.nlm.nih.gov/${result.reference.pmid})`
        : result.reference?.source || "N/A";

    rows.push(
      `| ${param} | ${result.confidence} | ${result.level} | ${(result.confidence * 100).toFixed(0)}% | ${source} |`,
    );
  }

  return rows.join("\n");
}
