/**
 * Literature Verifier
 * Ensures every returned parameter can be traced to peer-reviewed literature
 *
 * Three verification levels:
 * 1. VERIFIED: Parameter from literature (DOI, PMID, or URL provided)
 * 2. FLAGGED: Parameter from literature but missing assay conditions
 * 3. PENDING: Parameter from LLM - requires manual verification
 * 4. UNVERIFIABLE: Parameter is default/user-supplied (no literature backing)
 */

export type VerificationLevel = "verified" | "flagged" | "pending" | "unverifiable";

export interface LiteratureReference {
  doi?: string; // Digital Object Identifier
  pmid?: string; // PubMed ID
  url?: string; // Direct URL to source
  title?: string;
  authors?: string;
  year?: number;
  source?: string; // "brenda", "pubmed", "core", "llm", "user"
}

export interface VerificationResult {
  level: VerificationLevel;
  message: string;
  reference?: LiteratureReference;
  confidence: number; // 0-1 scale
  requiresManualReview: boolean;
}

/**
 * Verify a parameter against literature backing
 * BACKING: ADR 0011 - Parameter Provenance
 */
export function verifyParameterAgainstLiterature(
  parameterName: string,
  value: number,
  origin: "resolved" | "keyword" | "llm" | "user" | "default",
  reference?: LiteratureReference,
  assayConditionsComplete?: boolean,
): VerificationResult {
  // User-supplied parameters: no verification needed
  if (origin === "user") {
    return {
      level: "unverifiable",
      message: "Parameter supplied by user; trust as stated",
      confidence: 1.0,
      requiresManualReview: false,
    };
  }

  // Default parameters: lower confidence
  if (origin === "default") {
    return {
      level: "unverifiable",
      message: `Parameter is system default (${value}); not from literature`,
      confidence: 0.3,
      requiresManualReview: false,
    };
  }

  // LLM-supplied: requires manual verification
  if (origin === "llm") {
    return {
      level: "pending",
      message: "Parameter generated by LLM; requires manual literature verification before publication",
      reference,
      confidence: 0.4,
      requiresManualReview: true,
    };
  }

  // Keyword-matched: medium confidence
  if (origin === "keyword") {
    return {
      level: "flagged",
      message:
        "Parameter matched via keyword; not directly from literature. Use as estimate only.",
      reference,
      confidence: 0.6,
      requiresManualReview: false,
    };
  }

  // Resolved from literature (origin === "resolved")
  if (!reference || !reference.doi && !reference.pmid && !reference.url) {
    return {
      level: "flagged",
      message: "Parameter from literature but source not fully documented",
      reference,
      confidence: 0.7,
      requiresManualReview: false,
    };
  }

  // Full literature backing with DOI/PMID
  if (!assayConditionsComplete) {
    return {
      level: "flagged",
      message: `Parameter from ${reference.source || "literature"} but assay conditions incomplete (STRENDA Req 1-3)`,
      reference,
      confidence: 0.8,
      requiresManualReview: false,
    };
  }

  // Fully verified: literature + complete assay conditions
  return {
    level: "verified",
    message: `Parameter from ${reference.source || "literature"} with complete assay conditions per STRENDA`,
    reference,
    confidence: 0.95,
    requiresManualReview: false,
  };
}

/**
 * Get publication-ready verification message
 * Used when exporting results for peer review or publication
 */
export function getPublicationVerification(result: VerificationResult): string {
  switch (result.level) {
    case "verified":
      return `✅ ${result.message}. Confidence: ${(result.confidence * 100).toFixed(0)}%. ${result.reference?.doi ? `DOI: ${result.reference.doi}` : result.reference?.pmid ? `PMID: ${result.reference.pmid}` : ""}`;

    case "flagged":
      return `⚠️  ${result.message}. Confidence: ${(result.confidence * 100).toFixed(0)}%. Recommend obtaining complete assay conditions.`;

    case "pending":
      return `❌ ${result.message}. Confidence: ${(result.confidence * 100).toFixed(0)}%. DO NOT PUBLISH without manual verification.`;

    case "unverifiable":
      return `ℹ️  ${result.message}. Confidence: ${(result.confidence * 100).toFixed(0)}%.`;
  }
}

/**
 * Check if parameter can be safely published
 */
export function canPublish(result: VerificationResult): boolean {
  // Can publish if: verified OR flagged with literature + assay conditions
  if (result.level === "verified") return true;
  if (result.level === "flagged" && result.reference?.doi) return true; // Flagged but has DOI
  return false;
}

/**
 * Verify entire parameter set for publication
 */
export interface PublicationAudit {
  readyToPublish: boolean;
  verifiedCount: number;
  flaggedCount: number;
  pendingCount: number;
  unverifiableCount: number;
  summary: string;
  issues: string[];
}

export function auditForPublication(
  results: Record<string, VerificationResult>,
): PublicationAudit {
  let verifiedCount = 0;
  let flaggedCount = 0;
  let pendingCount = 0;
  let unverifiableCount = 0;
  const issues: string[] = [];

  for (const [param, result] of Object.entries(results)) {
    switch (result.level) {
      case "verified":
        verifiedCount++;
        break;
      case "flagged":
        flaggedCount++;
        issues.push(`${param}: ${result.message}`);
        break;
      case "pending":
        pendingCount++;
        issues.push(`${param}: ⚠️  REQUIRES MANUAL VERIFICATION - ${result.message}`);
        break;
      case "unverifiable":
        unverifiableCount++;
        break;
    }
  }

  const readyToPublish = pendingCount === 0 && (verifiedCount + flaggedCount > 0);

  return {
    readyToPublish,
    verifiedCount,
    flaggedCount,
    pendingCount,
    unverifiableCount,
    summary: readyToPublish
      ? `Publication ready: ${verifiedCount} verified, ${flaggedCount} with literature backing`
      : `Not ready: ${pendingCount} pending, ${unverifiableCount} unverifiable`,
    issues,
  };
}

/**
 * Generate publication-ready parameter table with verification status
 */
export function generatePublicationTable(
  results: Record<string, VerificationResult>,
): string {
  const rows: string[] = [
    "| Parameter | Value | Verification | Confidence | Source |",
    "|-----------|-------|--------------|------------|--------|",
  ];

  for (const [param, result] of Object.entries(results)) {
    const source = result.reference?.doi
      ? `[DOI](https://doi.org/${result.reference.doi})`
      : result.reference?.pmid
        ? `[PMID](https://pubmed.ncbi.nlm.nih.gov/${result.reference.pmid})`
        : result.reference?.source || "N/A";

    rows.push(
      `| ${param} | ${result.confidence} | ${result.level} | ${(result.confidence * 100).toFixed(0)}% | ${source} |`,
    );
  }

  return rows.join("\n");
}
