/**
 * Literature Verifier
 * Ensures every returned parameter can be traced to peer-reviewed literature
 *
 * Three verification levels:
 * 1. VERIFIED: Parameter from literature (DOI, PMID, or URL provided)
 * 2. FLAGGED: Parameter from literature but missing assay conditions
 * 3. PENDING: Parameter from LLM - requires manual verification
 * 4. UNVERIFIABLE: Parameter is default/user-supplied (no literature backing)
 */

export type VerificationLevel = "verified" | "flagged" | "pending" | "unverifiable";

export interface LiteratureReference {
  doi?: string; // Digital Object Identifier
  pmid?: string; // PubMed ID
  url?: string; // Direct URL to source
  title?: string;
  authors?: string;
  year?: number;
  source?: string; // "brenda", "pubmed", "core", "llm", "user"
}

export interface VerificationResult {
  level: VerificationLevel;
  message: string;
  reference?: LiteratureReference;
  confidence: number; // 0-1 scale
  requiresManualReview: boolean;
}

/**
 * Helper to create a verification result with consistent structure.
 */
function createVerificationResult(
  level: VerificationLevel,
  message: string,
  confidence: number,
  requiresManualReview: boolean,
  reference?: LiteratureReference,
): VerificationResult {
  return {
    level,
    message,
    reference,
    confidence,
    requiresManualReview,
  };
}

/**
 * Verify a parameter against literature backing
 * BACKING: ADR 0011 - Parameter Provenance
 */
export function verifyParameterAgainstLiterature(
  parameterName: string,
  value: number,
  origin: "resolved" | "keyword" | "llm" | "user" | "default",
  reference?: LiteratureReference,
  assayConditionsComplete?: boolean,
): VerificationResult {
  // User-supplied parameters: no verification needed
  if (origin === "user") {
    return createVerificationResult("unverifiable", "Parameter supplied by user; trust as stated", 1.0, false);
  }

  // Default parameters: lower confidence
  if (origin === "default") {
    return createVerificationResult(
      "unverifiable",
      `Parameter is system default (${value}); not from literature`,
      0.3,
      false,
    );
  }

  // LLM-supplied: requires manual verification
  if (origin === "llm") {
    return createVerificationResult(
      "pending",
      "Parameter generated by LLM; requires manual literature verification before publication",
      0.4,
      true,
      reference,
    );
  }

  // Keyword-matched: medium confidence
  if (origin === "keyword") {
    return createVerificationResult(
      "flagged",
      "Parameter matched via keyword; not directly from literature. Use as estimate only.",
      0.6,
      false,
      reference,
    );
  }

  // Resolved from literature (origin === "resolved")
  if (!reference || !reference.doi && !reference.pmid && !reference.url) {
    return createVerificationResult(
      "flagged",
      "Parameter from literature but source not fully documented",
      0.7,
      false,
      reference,
    );
  }

  // Full literature backing with DOI/PMID
  if (!assayConditionsComplete) {
    return createVerificationResult(
      "flagged",
      `Parameter from ${reference.source || "literature"} but assay conditions incomplete (STRENDA Req 1-3)`,
      0.8,
      false,
      reference,
    );
  }

  // Fully verified: literature + complete assay conditions
  return createVerificationResult(
    "verified",
    `Parameter from ${reference.source || "literature"} with complete assay conditions per STRENDA`,
    0.95,
    false,
    reference,
  );
}

/**
 * Get publication-ready verification message
 * Used when exporting results for peer review or publication
 */
export function getPublicationVerification(result: VerificationResult): string {
  switch (result.level) {
    case "verified":
      return `✅ ${result.message}. Confidence: ${(result.confidence * 100).toFixed(0)}%. ${result.reference?.doi ? `DOI: ${result.reference.doi}` : result.reference?.pmid ? `PMID: ${result.reference.pmid}` : ""}`;

    case "flagged":
      return `⚠️  ${result.message}. Confidence: ${(result.confidence * 100).toFixed(0)}%. Recommend obtaining complete assay conditions.`;

    case "pending":
      return `❌ ${result.message}. Confidence: ${(result.confidence * 100).toFixed(0)}%. DO NOT PUBLISH without manual verification.`;

    case "unverifiable":
      return `ℹ️  ${result.message}. Confidence: ${(result.confidence * 100).toFixed(0)}%.`;
  }
}

/**
 * Check if parameter can be safely published
 */
/**
 * Parameters that are experimental CONDITIONS, not measured properties.
 *
 * A paper states its substrate concentration; it does not cite one.
 * Nobody measures "the initial substrate concentration of this enzyme",
 * so requiring a citation for s0, [E]0 or pH before calling a parameter
 * set publication-ready is a category error -- the same one that made
 * Layer 1 of the validation pipeline reject every run with "Parameter
 * 's0' has no literature backing".
 *
 * What publication readiness means here is: every MEASURED quantity can
 * be cited. Conditions still have to be reported, and they appear in the
 * parameter table with `origin: "user"` so a reader can see they were
 * chosen rather than looked up.
 *
 * Kept as an explicit list rather than a heuristic, so a future measured
 * quantity cannot be exempted by accident.
 */
const EXPERIMENTAL_CONDITIONS: ReadonlySet<string> = new Set([
  "s0",
  "e0",
  "i0",
  "enzyme_conc",
  "temperature",
  "ph",
  "buffer",
]);

function isExperimentalCondition(name: string): boolean {
  return EXPERIMENTAL_CONDITIONS.has(name.toLowerCase());
}

export function canPublish(result: VerificationResult): boolean {
  // Can publish if: verified OR flagged with literature + assay conditions
  if (result.level === "verified") return true;
  if (result.level === "flagged" && result.reference?.doi) return true; // Flagged but has DOI
  return false;
}

/**
 * Verify entire parameter set for publication
 */
export interface PublicationAudit {
  readyToPublish: boolean;
  verifiedCount: number;
  flaggedCount: number;
  pendingCount: number;
  unverifiableCount: number;
  summary: string;
  issues: string[];
}

export function auditForPublication(
  results: Record<string, VerificationResult>,
): PublicationAudit {
  // Count results by level
  const counts: Record<VerificationLevel, number> = {
    verified: 0,
    flagged: 0,
    pending: 0,
    unverifiable: 0,
  };
  const issues: string[] = [];

  for (const [param, result] of Object.entries(results)) {
    counts[result.level]++;

    if (result.level === "flagged") {
      issues.push(`${param}: ${result.message}`);
    } else if (result.level === "pending") {
      issues.push(`${param}: ⚠️  REQUIRES MANUAL VERIFICATION - ${result.message}`);
    }
  }

  // Publication readiness is decided PER PARAMETER by `canPublish`, the
  // gate immediately above this function that requires a `flagged` value to
  // carry a DOI.
  //
  // This read `counts.pending === 0 && (counts.verified + counts.flagged > 0)`,
  // which was wrong in two ways and never called `canPublish` at all:
  //
  //   * `unverifiable` -- what `origin: "default"` and `origin: "user"`
  //     produce -- was counted, named in the summary string, and then
  //     ignored by the boolean. A set containing a system default reported
  //     ready.
  //   * `flagged` counted as equivalent to `verified`, but `flagged` is
  //     what verification returns for a KEYWORD-MATCHED value ("use as
  //     estimate only") and for a literature value with no DOI, PMID or
  //     URL. Those are exactly the values that must not appear in a paper
  //     uncited.
  //
  // So `{km: keyword-matched, vmax: keyword-matched, s0: default}` returned
  // readyToPublish: true with the summary "Publication ready: 0 verified,
  // 2 with literature backing" -- while `canPublish` was false for every
  // single one.
  //
  // Publication is a stricter bar than simulation, deliberately. A run may
  // proceed on a value you typed yourself (it is your bench data); a paper
  // may not present that value as literature-backed.
  const unpublishable = Object.entries(results).filter(
    ([param, result]) => !isExperimentalCondition(param) && !canPublish(result),
  );

  for (const [param, result] of unpublishable) {
    if (result.level !== "flagged" && result.level !== "pending") {
      issues.push(
        `${param}: not publishable -- ${result.level}` +
          (result.message ? ` (${result.message})` : ""),
      );
    }
  }

  const readyToPublish =
    unpublishable.length === 0 && Object.keys(results).length > 0;

  return {
    readyToPublish,
    verifiedCount: counts.verified,
    flaggedCount: counts.flagged,
    pendingCount: counts.pending,
    unverifiableCount: counts.unverifiable,
    summary: readyToPublish
      ? `Publication ready: ${counts.verified} verified, ${counts.flagged} flagged but citable`
      : `Not ready: ${unpublishable.length} of ${Object.keys(results).length} ` +
        `parameter(s) cannot be cited ` +
        `(${counts.pending} pending, ${counts.unverifiable} unverifiable, ` +
        `${counts.flagged} flagged without a DOI)`,
    issues,
  };
}

/**
 * Generate publication-ready parameter table with verification status
 */
export function generatePublicationTable(
  results: Record<string, VerificationResult>,
): string {
  const rows: string[] = [
    "| Parameter | Value | Verification | Confidence | Source |",
    "|-----------|-------|--------------|------------|--------|",
  ];

  for (const [param, result] of Object.entries(results)) {
    const source = result.reference?.doi
      ? `[DOI](https://doi.org/${result.reference.doi})`
      : result.reference?.pmid
        ? `[PMID](https://pubmed.ncbi.nlm.nih.gov/${result.reference.pmid})`
        : result.reference?.source || "N/A";

    rows.push(
      `| ${param} | ${result.confidence} | ${result.level} | ${(result.confidence * 100).toFixed(0)}% | ${source} |`,
    );
  }

  return rows.join("\n");
}
