"""Core data structures, validation, and utilities for the Terrium simulation engine."""

try:
    from .data_structures import (
        ModelBuildError,
        SimulationError,
        ParameterValidation,
        SimulationResult,
        KM_PLAUSIBLE_MIN_MM,
        KM_PLAUSIBLE_MAX_MM,
        R0_IMPLAUSIBLE_ABOVE,
        PCR_MIN_EFFICIENCY,
        PCR_MAX_EFFICIENCY,
        PCR_PLAUSIBLE_LOW_EFFICIENCY,
        MC_PLAUSIBLE_MIN_SAMPLES,
        WF_PLAUSIBLE_MIN_POPULATION_SIZE,
        WF_PLAUSIBLE_MAX_GENERATIONS,
        WF_PLAUSIBLE_MIN_REPLICATE_RUNS,
        WF_PLAUSIBLE_MAX_MUTATION_RATE,
        WF_PLAUSIBLE_MAX_SELECTION_COEFFICIENT,
        MD_PLAUSIBLE_MIN_PARTICLES,
        MD_PLAUSIBLE_MAX_TIMESTEP,
        MD_PLAUSIBLE_TEMPERATURE_LOW,
        MD_PLAUSIBLE_TEMPERATURE_HIGH,
        DEFAULT_RELATIVE_TOLERANCE,
        DEFAULT_ABSOLUTE_TOLERANCE,
        GAMMA_PARAM,
        _GAMMA_NOTE,
    )
    from .validation import (
        _finite_positive,
        validate_michaelis_menten_params,
        validate_sir_params,
        validate_seir_params,
        validate_pcr_params,
        validate_monte_carlo_params,
        validate_wright_fisher_params,
        validate_md_params,
    )
    from .utils import (
        _fmt,
        _RESERVED_MODEL_NAMES,
        _check_model_name,
        _load_runner,
    )
except (ModuleNotFoundError, ImportError):  # flat mode: Tellurium/ on sys.path, no repo root
    from core.data_structures import (
        ModelBuildError,
        SimulationError,
        ParameterValidation,
        SimulationResult,
        KM_PLAUSIBLE_MIN_MM,
        KM_PLAUSIBLE_MAX_MM,
        R0_IMPLAUSIBLE_ABOVE,
        PCR_MIN_EFFICIENCY,
        PCR_MAX_EFFICIENCY,
        PCR_PLAUSIBLE_LOW_EFFICIENCY,
        MC_PLAUSIBLE_MIN_SAMPLES,
        WF_PLAUSIBLE_MIN_POPULATION_SIZE,
        WF_PLAUSIBLE_MAX_GENERATIONS,
        WF_PLAUSIBLE_MIN_REPLICATE_RUNS,
        WF_PLAUSIBLE_MAX_MUTATION_RATE,
        WF_PLAUSIBLE_MAX_SELECTION_COEFFICIENT,
        MD_PLAUSIBLE_MIN_PARTICLES,
        MD_PLAUSIBLE_MAX_TIMESTEP,
        MD_PLAUSIBLE_TEMPERATURE_LOW,
        MD_PLAUSIBLE_TEMPERATURE_HIGH,
        DEFAULT_RELATIVE_TOLERANCE,
        DEFAULT_ABSOLUTE_TOLERANCE,
        GAMMA_PARAM,
        _GAMMA_NOTE,
    )
    from core.validation import (
        _finite_positive,
        validate_michaelis_menten_params,
        validate_sir_params,
        validate_seir_params,
        validate_pcr_params,
        validate_monte_carlo_params,
        validate_wright_fisher_params,
        validate_md_params,
    )
    from core.utils import (
        _fmt,
        _RESERVED_MODEL_NAMES,
        _check_model_name,
        _load_runner,
    )
