// GENERATED by scripts/refresh_export_samples.py -- do not edit by hand.
//
// Each sample is an excerpt of a real `caterva compose --export` run,
// cut the same way every time. Re-run the script after changing an
// exporter; the values are what BRENDA returned on the date below.

export interface ExportSample {
  format: "sbml" | "antimony" | "csv" | "methods";
  /** Which part of the file the excerpt is. */
  excerpt: string;
  /** The full file's size in bytes. */
  bytes: number;
  text: string;
}

export const EXPORT_COMMAND = "caterva compose \"Michaelis-Menten with a competitive inhibitor\" \\\n    --subject 1.1.1.27 --organism human --substrate pyruvate --inhibitor gossypol \\\n    --export";
export const EXPORT_RUN_DATE = "2026-09-29";

export const EXPORT_SAMPLES: ExportSample[] = [
  {
    "format": "sbml",
    "excerpt": "the Ki parameter and its notes",
    "bytes": 11058,
    "text": "<parameter metaid=\"caterva_reaction_Ki\" id=\"reaction_Ki\" value=\"0.0014\" constant=\"true\">\n  <notes>\n    <body xmlns=\"http://www.w3.org/1999/xhtml\">\n      <p>Measured in Homo sapiens.</p>\n      <p>\n        <strong>Not reported by the source: temperature, pH.</strong> A kinetic value cannot be reproduced or compared without them (STRENDA). This is a statement about the publication, not an omission by Caterva.</p>\n        <p>Source: BRENDA ref 711801</p>\n        <p>Resolution path: <code>literature</code></p>\n        <p>LITERATURE-DERIVED: BRENDA ref 711801; measured in Homo sapiens; resolved via literature; Caterva did not read the paper: this is the origin it was given, not a verification of it. SOURCE ROW: the row measured isoform LDH-B; if the enzyme you mean is another isoform, this is a different protein&apos;s constant. SOURCE ROW: the row states no inhibition mode, so whether it is the competitive constant this model uses is unknown. VALUES DISAGREE: one source (BRENDA ref 711801) reports 3 values, spanning 0.0014 to 0.0042 mM (3-fold); this model carries 0.0014, the resolver&apos;s pick, not a verdict; two rows from one publication usually differ in the conditions or the exact substrate, so read that paper before choosing. The range is not an uncertainty estimate: it is bounded by which rows are in the database.</p>\n      </body>\n    </notes>\n</parameter>\n"
  },
  {
    "format": "antimony",
    "excerpt": "the model block",
    "bytes": 6556,
    "text": "model michaelis_menten_with_a_competitive_inhibitor\n  species reaction_S, reaction_P, reaction_E, reaction_I;\n  reaction_catalysis: reaction_S -> reaction_P; reaction_kcat * reaction_E * reaction_S / (reaction_Km * (1 + reaction_I / reaction_Ki) + reaction_S);\n  reaction_S = 1.0;  // CHOSEN, NOT MEASURED: a starting amount, which is yours to set. No paper supplies it, so its absence from the literature is not a gap in this model.\n  reaction_P = 0.0;  // CHOSEN, NOT MEASURED: a starting amount, which is yours to set. No paper supplies it, so its absence from the literature is not a gap in this model.\n  reaction_E = 0.001;  // CHOSEN, NOT MEASURED: a starting amount, which is yours to set. No paper supplies it, so its absence from the literature is not a gap in this model.\n  reaction_I = 0.0;  // CHOSEN, NOT MEASURED: a starting amount, which is yours to set. No paper supplies it, so its absence from the literature is not a gap in this model.\n  reaction_kcat = 100.0;  // DEFAULT, not sourced -- ILLUSTRATIVE PLACEHOLDER: Caterva's motif library value for competitive_inhibition.kcat. No publication supplies this number and nobody measured it. It is here so the structure can be checked, dimensioned and simulated; the measurement that would replace it is in the kcat table.\n  reaction_Km = 0.03;  // literature; in Homo sapiens; BRENDA ref 286469\n  reaction_Ki = 0.0014;  // literature; in Homo sapiens; BRENDA ref 711801\nend\n"
  },
  {
    "format": "csv",
    "excerpt": "the header and the Ki row",
    "bytes": 3724,
    "text": "identifier,role,origin,value,unit,kind,resolvable_from_literature,motif,motif_symbol,what_it_is,source_table,citation,organism,cross_species,assay_ph,assay_temperature_c,assay_buffer,assay_not_reported_by_source,source_row_commentary,measured_isoform,inhibition_mode,inhibition_measured_versus,measured_preparation,reported_values_low,reported_values_high,reported_values_references,provenance\nreaction_Ki,parameter,measured,0.0014,mM,affinity,yes,competitive_inhibition,Ki,inhibitor dissociation constant,ki,BRENDA ref 711801,Homo sapiens,no,,,,\"temperature, pH\",\"LDH-B, pH not specified in the publication, temperature not specified in the publication\",LDH-B,unstated,,unstated,0.0014,0.0042,711801,\"LITERATURE-DERIVED: BRENDA ref 711801; measured in Homo sapiens; resolved via literature; Caterva did not read the paper: this is the origin it was given, not a verification of it. SOURCE ROW: the row measured isoform LDH-B; if the enzyme you mean is another isoform, this is a different protein's constant. SOURCE ROW: the row states no inhibition mode, so whether it is the competitive constant this model uses is unknown. VALUES DISAGREE: one source (BRENDA ref 711801) reports 3 values, spanning 0.0014 to 0.0042 mM (3-fold); this model carries 0.0014, the resolver's pick, not a verdict; two rows from one publication usually differ in the conditions or the exact substrate, so read that paper before choosing. The range is not an uncertainty estimate: it is bounded by which rows are in the database.\"\n"
  },
  {
    "format": "methods",
    "excerpt": "the section \"Where every constant came from\"",
    "bytes": 3206,
    "text": "### Where every constant came from\n\n**LITERATURE-DERIVED (2 of 3).** Each of the following was taken from the cited source; Caterva recorded the citation and did not verify that the source reports the value:\n\n- `reaction_Km` = 0.03 mM (BRENDA ref 286469, measured in Homo sapiens)\n  - The values disagree: 2 sources report 2 values (BRENDA ref 286442, 286469), spanning 0.03 to 0.398 mM (13.3-fold); this model carries 0.03, the resolver's pick, not a verdict; which one is right is a question about the papers. The range is not an uncertainty estimate: it is bounded by which rows are in the database.\n- `reaction_Ki` = 0.0014 mM (BRENDA ref 711801, measured in Homo sapiens)\n  - The row measured isoform LDH-B; if the enzyme you mean is another isoform, this is a different protein's constant.\n  - The row states no inhibition mode, so whether it is the competitive constant this model uses is unknown.\n  - The values disagree: one source (BRENDA ref 711801) reports 3 values, spanning 0.0014 to 0.0042 mM (3-fold); this model carries 0.0014, the resolver's pick, not a verdict; two rows from one publication usually differ in the conditions or the exact substrate, so read that paper before choosing. The range is not an uncertainty estimate: it is bounded by which rows are in the database.\n\n**ILLUSTRATIVE PLACEHOLDERS (1 of 3). These are not measurements. No publication supplies them and nobody measured them; they are Caterva's motif library values, present so that the structure could be checked, dimensioned and simulated:**\n\n- `reaction_kcat` = 100 1/s -- competitive_inhibition.kcat; the kcat table would supply it\n\nAny result that depends on these values is a statement about the shape of the mechanism rather than about a particular real system, and should be read as one.\n"
  }
];
