#!/usr/bin/env python3
"""Codegen guard: the generated API contract must load, and must be current.

WHY THIS EXISTS
---------------
`lib/api-zod/src/generated/api.ts` is the zod schema every request is parsed
against. It is generated by orval from `lib/api-spec/openapi.yaml`, it is
committed, and until this guard nothing checked either half of that
arrangement.

Both halves had failed.

**It did not load.** orval's `override.zod.version` defaults to `"auto"`,
which inspects the installed zod. zod 3.25 ships a `zod/v4` subpath, so
detection concluded v4 and emitted `zod.iso.datetime(...)` — while still
importing from plain `"zod"`, where `iso` is `undefined`. Running the
documented `pnpm --filter @workspace/api-spec run codegen` produced a
contract package that threw on import. The only reason nobody hit it is that
the committed files predate the zod bump and nobody had regenerated.

Proven rather than assumed, by loading a freshly generated module:

    RESULT: FAILED -> Cannot read properties of undefined (reading 'datetime')

**It was stale.** Even with the version pinned, the committed files and the
regenerated ones disagree: `zod.coerce.date()` against
`zod.string().datetime({ offset: true })`. Both are valid zod 3 and they are
not the same validator — one coerces a string into a Date, the other
validates a string and leaves it a string. A caller reading `completedAt`
gets a different type depending on which file is in the tree.

WHY A GUARD AND NOT A FIX
-------------------------
The staleness IS fixable by regenerating. The reason this is a guard is that
regenerating fixes it once, and nothing stops it recurring — generated files
that nobody regenerates drift silently by construction, and the drift is
normally discovered by someone running codegen for an unrelated reason and
finding a diff they did not cause.

WHAT THIS DOES NOT DO
---------------------
It does not regenerate anything under `lib/`. A guard that repairs what it
inspects cannot report, and a guard that overwrites the contract on the way
to failing leaves the tree worse than it found it. Output goes to a scratch
directory; the fix is a human running codegen and reading the diff.

It also does not check `api-client-react`. That project generates React
Query hooks whose output depends on a second toolchain, and the zod schema is
the one that gates every request at run time. Checking one thing properly is
worth more than checking two things approximately — and saying which one is
unchecked is worth more than implying both are.

Exit codes:
    0  generated contract loads and matches the committed files
    1  it does not (message says which)
    2  the check could not run (orval missing, node missing) — NOT a pass
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
API_SPEC = REPO_ROOT / "Science-Agent-Pipeline" / "lib" / "api-spec"
COMMITTED = (
    REPO_ROOT
    / "Science-Agent-Pipeline"
    / "lib"
    / "api-zod"
    / "src"
    / "generated"
    / "api.ts"
)
VERIFY_CONFIG = API_SPEC / "orval.probe.config.ts"

#: A check that could not run is not a check that passed. Every early exit
#: below uses this, and none of them return 0.
COULD_NOT_RUN = 2


def _fail_to_run(message: str) -> int:
    print(f"CANNOT VERIFY: {message}")
    print(
        "\nThis is exit 2, not exit 0. A codegen check that silently passes "
        "when it could not run is how the broken contract survived in the "
        "first place."
    )
    return COULD_NOT_RUN


def _module_loads(path: Path, env: dict) -> tuple[bool, str]:
    """`(loaded, detail)` for one generated module.

    Imported directly from wherever it sits, with NODE_PATH pointing at
    lib/api-zod's node_modules so `zod` resolves exactly as it will for the
    real package.
    """
    api_zod = REPO_ROOT / "Science-Agent-Pipeline" / "lib" / "api-zod"
    node_path = os.pathsep.join(
        [
            str(api_zod / "node_modules"),
            str(REPO_ROOT / "Science-Agent-Pipeline" / "node_modules"),
        ]
    )
    proc = subprocess.run(
        [
            "npx",
            "tsx",
            "-e",
            f"import({json.dumps(str(path))})"
            ".then(() => console.log('LOAD_OK'))"
            ".catch(e => { console.log('LOAD_FAIL:' + (e && e.message)); "
            "process.exitCode = 1; });",
        ],
        cwd=str(api_zod),
        capture_output=True,
        text=True,
        timeout=600,
        env={**env, "NODE_PATH": node_path},
    )
    if "LOAD_OK" in proc.stdout:
        return True, ""
    detail = ""
    for line in proc.stdout.splitlines():
        if line.startswith("LOAD_FAIL:"):
            detail = line[len("LOAD_FAIL:") :].strip()
    return False, detail or (proc.stderr or proc.stdout)[-400:]


def selftest() -> int:
    """Prove the load check can fail.

    WHY THIS EXISTS
    ---------------
    The load branch has never fired in anger since the config was pinned, and
    I could not construct an orval config that makes it fire: `version: 4`,
    removing the coercion block, and dropping the whole override all produce
    modules that load. So the branch was **unfalsifiable** — present, plausible,
    and indistinguishable from a branch that does nothing.

    This project's rule is that a check which cannot fail is worse than no
    check, because it is trusted. That rule applies to this file.

    So the failure is constructed directly: a module using `zod.iso.datetime`,
    which is exactly what orval emitted before `override.zod.version` was
    pinned, and exactly what threw

        Cannot read properties of undefined (reading 'datetime')

    when a real generated file was loaded earlier today. If the load check
    cannot reject this, it cannot reject anything.
    """
    with tempfile.TemporaryDirectory() as tmp:
        broken = Path(tmp) / "broken.ts"
        broken.write_text(
            'import * as zod from "zod";\n'
            "// zod 3.25 has no `iso` namespace; this is what orval's `auto`\n"
            "// detection emitted, and it throws at module scope.\n"
            "export const Broken = zod.object({\n"
            "  when: (zod as any).iso.datetime({ offset: true }),\n"
            "});\n"
        )
        ok, detail = _module_loads(broken, dict(os.environ))
        if ok:
            print(
                "SELFTEST FAILED: the load check accepted a module that uses "
                "`zod.iso.datetime`, which cannot work against the installed "
                "zod. The check is not detecting load failures."
            )
            return 1

        good = Path(tmp) / "good.ts"
        good.write_text(
            'import * as zod from "zod";\n'
            "export const Fine = zod.object({ when: zod.coerce.date() });\n"
        )
        ok, _ = _module_loads(good, dict(os.environ))
        if not ok:
            print(
                "SELFTEST FAILED: the load check rejected a module that is "
                "valid for the installed zod. It would report false failures."
            )
            return 1

    print("SELFTEST OK: the load check rejects a broken module and accepts a "
          "working one.")
    print(f"  rejection detail: {detail}")
    return 0


def main() -> int:
    if not VERIFY_CONFIG.exists():
        return _fail_to_run(f"{VERIFY_CONFIG.relative_to(REPO_ROOT)} is missing")
    if not COMMITTED.exists():
        return _fail_to_run(f"{COMMITTED.relative_to(REPO_ROOT)} is missing")
    if shutil.which("npx") is None:
        return _fail_to_run("npx is not on PATH")

    with tempfile.TemporaryDirectory() as tmp:
        env = {**os.environ, "ORVAL_VERIFY_OUT": tmp}
        print("Regenerating the contract into a scratch directory...")
        gen = subprocess.run(
            ["npx", "orval", "--config", "./orval.probe.config.ts"],
            cwd=str(API_SPEC),
            capture_output=True,
            text=True,
            timeout=600,
            env=env,
        )
        produced = Path(tmp) / "api-zod" / "src" / "generated" / "api.ts"
        if gen.returncode != 0 or not produced.exists():
            return _fail_to_run(
                "orval did not produce an output file.\n"
                + (gen.stderr or gen.stdout)[-800:]
            )

        generated_text = produced.read_text()

        # --- 1. Does it load? -------------------------------------------
        loaded, detail = _module_loads(produced, env)
        if not loaded:
            print("The generated API contract does not load.\n")
            print(f"  {detail}")
            print(
                "\nEvery request the API server accepts is parsed against this "
                "schema. A contract that throws on import is not a degraded "
                "build, it is no build.\n"
                "\nMost likely cause: `override.zod.version` in "
                "orval.config.ts disagrees with the installed zod. Check with:"
                "\n  node -e \"const z=require('zod'); console.log(typeof z.iso)\""
            )
            return 1

        # --- 2. Is the committed copy current? --------------------------
        committed_text = COMMITTED.read_text()
        if committed_text == generated_text:
            print("OK: the generated contract loads, and the committed copy "
                  "is byte-identical to what codegen produces.")
            return 0

        committed_lines = committed_text.splitlines()
        generated_lines = generated_text.splitlines()
        differing = sum(
            1
            for a, b in zip(committed_lines, generated_lines)
            if a != b
        ) + abs(len(committed_lines) - len(generated_lines))

        print(
            "The committed contract is not what codegen produces "
            f"({differing} line(s) differ).\n"
        )
        shown = 0
        for index, (a, b) in enumerate(zip(committed_lines, generated_lines), 1):
            if a == b:
                continue
            print(f"  line {index}")
            print(f"    committed: {a.strip()[:100]}")
            print(f"    codegen:   {b.strip()[:100]}")
            shown += 1
            if shown >= 6:
                print("  ...")
                break

        print(
            "\nThese are not cosmetic. `zod.coerce.date()` and "
            "`zod.string().datetime(...)` are different validators: one "
            "coerces a string into a Date, the other validates a string and "
            "leaves it a string. A caller reading a timestamp gets a "
            "different type depending on which file is in the tree.\n"
            "\nFix by regenerating and reading the diff:\n"
            "  pnpm --filter @workspace/api-spec run codegen"
        )
        return 1


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        sys.exit(selftest())
    sys.exit(main())
