#!/usr/bin/env python3
"""Regenerate the landing page's export samples from a real `caterva compose` run.

The page's export panel once showed an SBML file with Km 2.0 and Vmax 5.0
"from BRENDA" and a PMID of 12345678: teaching defaults and a placeholder,
presented as provenance, on the page whose claim is that provenance is never
invented. Then it showed hand-trimmed excerpts of a real run, which were
honest on the day and nobody could regenerate.

This runs the README's headline command once per export format, cuts the
same excerpt from each every time, and writes them to
`caterva-landing/src/lib/exportSamples.ts` with the command, the date, and
each full file's size. Nothing in that file is typed by a person.

It needs the network (BRENDA is queried live), so it is not part of CI.
Run it after changing an exporter, and commit the result:

    python scripts/refresh_export_samples.py
"""
from __future__ import annotations

import datetime as _dt
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Callable, Dict, List

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "Science-Agent-Pipeline" / "artifacts" / "caterva-landing" / "src" / "lib" / "exportSamples.ts"

QUERY = "Michaelis-Menten with a competitive inhibitor"
ARGS = ["--subject", "1.1.1.27", "--organism", "human", "--substrate", "pyruvate",
        "--inhibitor", "gossypol"]
COMMAND = (f'caterva compose "{QUERY}" \\\n    --subject 1.1.1.27 --organism human '
           f'--substrate pyruvate --inhibitor gossypol \\\n    --export')


def _between(text: str, start: str, end: str, *, include_end: bool = True) -> str:
    """The lines from the first starting with `start` to the next starting
    with `end`. Refuses rather than returning something shorter when either
    is missing: an exporter that changed shape must be looked at."""
    lines = text.splitlines()
    try:
        a = next(i for i, l in enumerate(lines) if l.lstrip().startswith(start))
        b = next(i for i in range(a + 1, len(lines)) if lines[i].lstrip().startswith(end))
    except StopIteration:
        raise SystemExit(f"excerpt markers {start!r} .. {end!r} not found; the export changed shape")
    chunk = lines[a:b + 1] if include_end else lines[a:b]
    indent = min(len(l) - len(l.lstrip()) for l in chunk if l.strip())
    return "\n".join(l[indent:] for l in chunk).rstrip() + "\n"


def _csv(text: str) -> str:
    lines = text.splitlines()
    ki = [l for l in lines if l.startswith("reaction_Ki,")]
    if not ki:
        raise SystemExit("no reaction_Ki row in the CSV export")
    return lines[0] + "\n" + ki[0] + "\n"


#: format -> (what the excerpt is, how to cut it)
EXCERPTS: Dict[str, tuple] = {
    "sbml": ("the Ki parameter and its notes",
             lambda t: _between(t, '<parameter metaid="caterva_reaction_Ki"', "</parameter>")),
    "antimony": ("the model block",
                 lambda t: _between(t, "model ", "end")),
    "csv": ("the header and the Ki row", _csv),
    "methods": ('the section "Where every constant came from"',
                lambda t: _between(t, "### Where every constant came from", "Any result")),
}


def run(fmt: str) -> str:
    proc = subprocess.run([sys.executable, "-m", "caterva.compose", QUERY, *ARGS, "--export", fmt],
                          cwd=REPO, capture_output=True, text=True, timeout=600)
    if proc.returncode != 0:
        raise SystemExit(f"--export {fmt} failed ({proc.returncode}):\n{proc.stderr[-2000:]}")
    return proc.stdout


def render(samples: List[dict], today: str) -> str:
    body = json.dumps(samples, indent=2, ensure_ascii=False)
    return (
        "// GENERATED by scripts/refresh_export_samples.py -- do not edit by hand.\n"
        "//\n"
        "// Each sample is an excerpt of a real `caterva compose --export` run,\n"
        "// cut the same way every time. Re-run the script after changing an\n"
        "// exporter; the values are what BRENDA returned on the date below.\n"
        "\n"
        "export interface ExportSample {\n"
        "  format: \"sbml\" | \"antimony\" | \"csv\" | \"methods\";\n"
        "  /** Which part of the file the excerpt is. */\n"
        "  excerpt: string;\n"
        "  /** The full file's size in bytes. */\n"
        "  bytes: number;\n"
        "  text: string;\n"
        "}\n"
        "\n"
        f"export const EXPORT_COMMAND = {json.dumps(COMMAND)};\n"
        f"export const EXPORT_RUN_DATE = {json.dumps(today)};\n"
        "\n"
        f"export const EXPORT_SAMPLES: ExportSample[] = {body};\n"
    )


def main() -> int:
    samples = []
    for fmt, (what, cut) in EXCERPTS.items():
        text = run(fmt)
        samples.append({"format": fmt, "excerpt": what, "bytes": len(text.encode()), "text": cut(text)})
        print(f"{fmt}: {len(text.encode())} bytes, excerpt {len(samples[-1]['text'])} chars")
    OUT.write_text(render(samples, _dt.date.today().isoformat()))
    print(f"wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
